name: skillpp_kelas12
description: "Skill passport kelas 12"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets: 
  - assets/logo.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true